version: 2

project_name: gitlab-file-scanner

builds:
- id: default
  main: ./cmd
  binary: gitlab-file-scanner
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -X gitlabFileScanner/internal/cli/commands.version={{ .Version }}
  - -X gitlabFileScanner/internal/cli/commands.commit={{ .Commit }}
  - -X gitlabFileScanner/internal/cli/commands.branch=release
  - -X gitlabFileScanner/internal/cli/commands.buildDate={{ .Date }}

archives:
- id: default
  formats: [ "tar.gz" ]
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format_overrides:
  - goos: windows
    formats: [ "zip" ]
  files:
  - LICENSE
  - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  disable: true

changelog:
  disable: true
